AIBParameters: expand "build_dir" path to get rid of "~" prefix
Currently, "build_dir" might contain "~" prefix.
This causes run-time failure when trying to create a temp
directory, which is required for the build process:
PermissionError: [Errno 13] Permission denied: '~/build/20240729_170327'
Added the "build_dir" cached property that expands the path.

Additionally, removed a few unused imports.

Signed-off-by: Pavel Bar <pbar@redhat.com>